version: '2'
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'hasithaishere/buildkite-file-counter']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"