#!/bin/bash
set -euo pipefail

if ! command -v biey &> /dev/null
then
    echo -e "Bie CLI tool not installed, Please install the CLI in Buildkite agent first.\nFor more information-\nhttps://github.com/respond-io/buildkite-iac-executor",

else
    echo "Bie command found"
fi

PATTERN="$BUILDKITE_PLUGIN_BUILDKITE_FILE_COUNTER_PATTERN"

echo "--- :1234: Counting the number of files"

COUNT=$(find . -name "$PATTERN" | wc -l)

echo "Found ${COUNT} files matching ${PATTERN}"

buildkite-agent annotate "Found ${COUNT} files matching ${PATTERN}"
