#!/bin/bash
set -euo pipefail

if ! command -v biey &> /dev/null
then
    ERR_MESSAGE="⚠ Bie CLI tool not installed, Please install the CLI in Buildkite agent first.<br>\nFor more information-\nhttps://github.com/respond-io/buildkite-iac-executor"
    buildkite-agent annotate "$ERR_MESSAGE"
    echo -e $ERR_MESSAGE
    exit 1
else
    echo "Bie command found"
fi

PATTERN="$BUILDKITE_PLUGIN_BUILDKITE_FILE_COUNTER_PATTERN"

echo "--- :1234: Counting the number of files"

COUNT=$(find . -name "$PATTERN" | wc -l)

echo "Found ${COUNT} files matching ${PATTERN}"

buildkite-agent annotate "Found ${COUNT} files matching ${PATTERN}"
