#!/bin/bash
set -euo pipefail

if ! command -v bie &> /dev/null
then
    echo "Bie could not be found"
else
    echo "Bie command found"
fi

PATTERN="$BUILDKITE_PLUGIN_BUILDKITE_FILE_COUNTER_PATTERN"

echo "--- :1234: Counting the number of files"

COUNT=$(find . -name "$PATTERN" | wc -l)

echo "Found ${COUNT} files matching ${PATTERN}"

buildkite-agent annotate "Found ${COUNT} files matching ${PATTERN}"
